# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6541e9d41b35bbfa388dba4a2c357a2b797392adef59ca505bf755b6fc60ec08b43387693088503438f673d4f7f5a2641c2a17c56ee42fdc73b703b018f96af7

test:
  secret_key_base: 96802b4005325e8d6827bea026be55095b559146b1096967a1cc0aa339f4a146b1671641629119970609f45eed391fe4375cc40604e32247985395fc921fb4a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
